version: '2'
services:
    echoquebec-app:
        image: echoquebec
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://echoquebec-mysql:3306/echoquebec?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    echoquebec-mysql:
        extends:
            file: mysql.yml
            service: echoquebec-mysql
